joint_limits:
  left_e0:
    has_velocity_limits: false
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 4.0
  left_e1:
    has_velocity_limits: false
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 4.0
  left_s0:
    has_velocity_limits: false
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 4.0
  left_s1:
    has_velocity_limits: false
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 4.0
  left_w0:
    has_velocity_limits: false
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 4.0
  left_w1:
    has_velocity_limits: false
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 4.0
  left_w2:
    has_velocity_limits: false
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 4.0
  right_e0:
    has_velocity_limits: false
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 4.0
  right_e1:
    has_velocity_limits: false
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 4.0
  right_s0:
    has_velocity_limits: false
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 4.0
  right_s1:
    has_velocity_limits: false
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 4.0
  right_w0:
    has_velocity_limits: false
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 4.0
  right_w1:
    has_velocity_limits: false
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 4.0
  right_w2:
    has_velocity_limits: false
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 4.0
